version: '3.8'

services:
  spring-boot-app:
    image: openjdk:17-jdk-alpine
    volumes:
      - ./target:/app
    ports:
      - "8097:8080"
    expose:
      - "8097"
    command: ["java", "-jar", "/app/MS-Clientes-0.0.1-SNAPSHOT.jar"]
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/clientedatabase
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=secret
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: clientedatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret